package org.arise.goal;

public enum Area {
    CAREER,
    HEALTH,
    RELATIONSHIP,
    FINANCE,
    PERSONAL_DEVELOPMENT,
    SPIRITUALITY,
    FUN_RECREATION,
    PHYSICAL_ENVIRONMENT,
    COMMUNITY_INVOLVEMENT
}
