# Default to local development
spring.profiles.active=local

# Common Settings
spring.config.import=optional:file:../.env[.properties]
springdoc.api-docs.version=openapi_3_0
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

# Auth
lifeos.auth.username=${LIFEOS_AUTH_USERNAME}
lifeos.auth.password=${LIFEOS_AUTH_PASSWORD}